<template>
    <div
        class="bt-view__table"
        style="box-sizing: border-box; width: 100%; height: 100%; padding: 50px"
    >
        <el-button @click="resetQueryParam">重置高级搜索</el-button>
        <el-button @click="getQueryParam">获取高级搜索条件</el-button>
        <!-- :static-data="staticData" -->
        <BtTable2
            ref="proTable"
            :init-param="initParam"
            table-id="1"
            sence-id="2"
            :sence-info="senceInfo"
            :search-columns="masterSearchColumns"
            :columns="columns"
            :search-bar="true"
            :search-bar-props="{
                isSenior: true,
                isToolColumn: true,
            }"
            :enable-static-data="true"
            :request-api="requestApi"
            row-key="detailId"
            :init-loading="false"
            :column-setting="true"
            :highlight-current-row="hightLightCurrentRow"
            @search-bar-change="searchBarChange"
        >
            <template #tableHeaderLeft>
                <bt-button type="primary">新&nbsp;&nbsp;增</bt-button>
            </template>
            <template #tableHeaderRight>
                <bt-button type="primary">新&nbsp;&nbsp;增</bt-button>
            </template>
        </BtTable2>
    </div>
</template>

<script setup lang="ts" name="useComponent">
import { reactive, ref } from 'vue'
const staticData = ref([]) as any
const hightLightCurrentRow = true

const initParam: any = reactive({
    // pageNumber: 1,
    // pageSize: 1000,
    code: '',
})
const requestApi = param => {
    console.log(param, 'param....')
    return new Promise<any>(resolve => {
        return resolve({
            code: 0,
            msg: '',
            data: {
                current: 2,
                size: 50,
                total: 250,
                pages: 5,
                records: [
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '克',
                        deputyUnit: null,
                        detailId: '6b4f2a0ec6450902ac81e22061600095',
                        drawingNo: null,
                        gmtCreate: '2023-08-10 16:00:08',
                        id: '22dd46486269cd7648f1973bca563098',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'cb81e82c625795853e1a7f5ac3303410',
                        materialName: 'LL2307170003',
                        materialNo: 'Material00174',
                        materialTypeName: '自制材料',
                        model: null,
                        region: null,
                        serialNo: 'Material00174-20230810-10',
                        sharpeningCount: 0,
                        specs: null,
                        status: '1',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: null,
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '克',
                        deputyUnit: null,
                        detailId: '81754e4e04093fbe22af96d4d690716d',
                        drawingNo: null,
                        gmtCreate: '2023-08-10 16:00:08',
                        id: '22dd46486269cd7648f1973bca563098',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'cb81e82c625795853e1a7f5ac3303410',
                        materialName: 'LL2307170003',
                        materialNo: 'Material00174',
                        materialTypeName: '自制材料',
                        model: null,
                        region: null,
                        serialNo: 'Material00174-20230810-09',
                        sharpeningCount: 0,
                        specs: null,
                        status: '1',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: null,
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '克',
                        deputyUnit: null,
                        detailId: 'ee3e22088c749a3fa33119b81ca8e277',
                        drawingNo: null,
                        gmtCreate: '2023-08-10 16:00:08',
                        id: '22dd46486269cd7648f1973bca563098',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'cb81e82c625795853e1a7f5ac3303410',
                        materialName: 'LL2307170003',
                        materialNo: 'Material00174',
                        materialTypeName: '自制材料',
                        model: null,
                        region: null,
                        serialNo: 'Material00174-20230810-08',
                        sharpeningCount: 0,
                        specs: null,
                        status: '1',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: null,
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '克',
                        deputyUnit: null,
                        detailId: '75814db367774ba9554ed33a6452f9aa',
                        drawingNo: null,
                        gmtCreate: '2023-08-10 16:00:08',
                        id: '22dd46486269cd7648f1973bca563098',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'cb81e82c625795853e1a7f5ac3303410',
                        materialName: 'LL2307170003',
                        materialNo: 'Material00174',
                        materialTypeName: '自制材料',
                        model: null,
                        region: null,
                        serialNo: 'Material00174-20230810-07',
                        sharpeningCount: 0,
                        specs: null,
                        status: '1',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: null,
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '克',
                        deputyUnit: null,
                        detailId: '7721466aeb07ebc20d31f2dfbe5836be',
                        drawingNo: null,
                        gmtCreate: '2023-08-10 16:00:08',
                        id: '22dd46486269cd7648f1973bca563098',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'cb81e82c625795853e1a7f5ac3303410',
                        materialName: 'LL2307170003',
                        materialNo: 'Material00174',
                        materialTypeName: '自制材料',
                        model: null,
                        region: null,
                        serialNo: 'Material00174-20230810-06',
                        sharpeningCount: 0,
                        specs: null,
                        status: '3',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: null,
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '克',
                        deputyUnit: null,
                        detailId: 'b9711cda3a277ecf34c6f7c63a983e40',
                        drawingNo: null,
                        gmtCreate: '2023-08-10 16:00:08',
                        id: '22dd46486269cd7648f1973bca563098',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'cb81e82c625795853e1a7f5ac3303410',
                        materialName: 'LL2307170003',
                        materialNo: 'Material00174',
                        materialTypeName: '自制材料',
                        model: null,
                        region: null,
                        serialNo: 'Material00174-20230810-05',
                        sharpeningCount: 0,
                        specs: null,
                        status: '3',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: null,
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '克',
                        deputyUnit: null,
                        detailId: 'da45c19a712a7928c14be01a3ad50484',
                        drawingNo: null,
                        gmtCreate: '2023-08-10 16:00:08',
                        id: '22dd46486269cd7648f1973bca563098',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'cb81e82c625795853e1a7f5ac3303410',
                        materialName: 'LL2307170003',
                        materialNo: 'Material00174',
                        materialTypeName: '自制材料',
                        model: null,
                        region: null,
                        serialNo: 'Material00174-20230810-04',
                        sharpeningCount: 0,
                        specs: null,
                        status: '2',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: null,
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '克',
                        deputyUnit: null,
                        detailId: '4c4843a89bc608073b3eba4c9158bfc8',
                        drawingNo: null,
                        gmtCreate: '2023-08-10 16:00:08',
                        id: '22dd46486269cd7648f1973bca563098',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'cb81e82c625795853e1a7f5ac3303410',
                        materialName: 'LL2307170003',
                        materialNo: 'Material00174',
                        materialTypeName: '自制材料',
                        model: null,
                        region: null,
                        serialNo: 'Material00174-20230810-03',
                        sharpeningCount: 0,
                        specs: null,
                        status: '2',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: null,
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '克',
                        deputyUnit: null,
                        detailId: 'd253977d299744302ced976cb7a93b57',
                        drawingNo: null,
                        gmtCreate: '2023-08-10 16:00:08',
                        id: '22dd46486269cd7648f1973bca563098',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'cb81e82c625795853e1a7f5ac3303410',
                        materialName: 'LL2307170003',
                        materialNo: 'Material00174',
                        materialTypeName: '自制材料',
                        model: null,
                        region: null,
                        serialNo: 'Material00174-20230810-02',
                        sharpeningCount: 0,
                        specs: null,
                        status: '2',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: null,
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '克',
                        deputyUnit: null,
                        detailId: '8560661c1e71567097afbb510974f857',
                        drawingNo: null,
                        gmtCreate: '2023-08-10 16:00:08',
                        id: '22dd46486269cd7648f1973bca563098',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'cb81e82c625795853e1a7f5ac3303410',
                        materialName: 'LL2307170003',
                        materialNo: 'Material00174',
                        materialTypeName: '自制材料',
                        model: null,
                        region: null,
                        serialNo: 'Material00174-20230810-01',
                        sharpeningCount: 0,
                        specs: null,
                        status: '4',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: null,
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '条',
                        deputyUnit: null,
                        detailId: '60255528a822aa9c66702da752742a76',
                        drawingNo: 'LL2307170001图号',
                        gmtCreate: '2023-08-10 16:00:07',
                        id: '7d92a2dfbe50a4e06a4396d786dd5b86',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'bfefd2c6f790e582c2988d07df11e8f4',
                        materialName: 'LL2307170001',
                        materialNo: 'Material00172',
                        materialTypeName: '原材料',
                        model: 'LL2307170001型号',
                        region: null,
                        serialNo: 'Material00172-20230810-10',
                        sharpeningCount: 0,
                        specs: 'LL2307170001规格',
                        status: '1',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: 'LL2307170001材质',
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '条',
                        deputyUnit: null,
                        detailId: '315607b201c69e61edf8c5aebb6d8962',
                        drawingNo: 'LL2307170001图号',
                        gmtCreate: '2023-08-10 16:00:07',
                        id: '7d92a2dfbe50a4e06a4396d786dd5b86',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'bfefd2c6f790e582c2988d07df11e8f4',
                        materialName: 'LL2307170001',
                        materialNo: 'Material00172',
                        materialTypeName: '原材料',
                        model: 'LL2307170001型号',
                        region: null,
                        serialNo: 'Material00172-20230810-09',
                        sharpeningCount: 0,
                        specs: 'LL2307170001规格',
                        status: '1',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: 'LL2307170001材质',
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '条',
                        deputyUnit: null,
                        detailId: 'b1e2836555e82f42fb086d48042007d7',
                        drawingNo: 'LL2307170001图号',
                        gmtCreate: '2023-08-10 16:00:07',
                        id: '7d92a2dfbe50a4e06a4396d786dd5b86',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'bfefd2c6f790e582c2988d07df11e8f4',
                        materialName: 'LL2307170001',
                        materialNo: 'Material00172',
                        materialTypeName: '原材料',
                        model: 'LL2307170001型号',
                        region: null,
                        serialNo: 'Material00172-20230810-08',
                        sharpeningCount: 0,
                        specs: 'LL2307170001规格',
                        status: '1',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: 'LL2307170001材质',
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '条',
                        deputyUnit: null,
                        detailId: 'eff04eb555df95ef86621310430f4a19',
                        drawingNo: 'LL2307170001图号',
                        gmtCreate: '2023-08-10 16:00:07',
                        id: '7d92a2dfbe50a4e06a4396d786dd5b86',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'bfefd2c6f790e582c2988d07df11e8f4',
                        materialName: 'LL2307170001',
                        materialNo: 'Material00172',
                        materialTypeName: '原材料',
                        model: 'LL2307170001型号',
                        region: null,
                        serialNo: 'Material00172-20230810-07',
                        sharpeningCount: 0,
                        specs: 'LL2307170001规格',
                        status: '1',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: 'LL2307170001材质',
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '条',
                        deputyUnit: null,
                        detailId: '4213e3659478d787081b3b7b7478212c',
                        drawingNo: 'LL2307170001图号',
                        gmtCreate: '2023-08-10 16:00:07',
                        id: '7d92a2dfbe50a4e06a4396d786dd5b86',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'bfefd2c6f790e582c2988d07df11e8f4',
                        materialName: 'LL2307170001',
                        materialNo: 'Material00172',
                        materialTypeName: '原材料',
                        model: 'LL2307170001型号',
                        region: null,
                        serialNo: 'Material00172-20230810-06',
                        sharpeningCount: 0,
                        specs: 'LL2307170001规格',
                        status: '1',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: 'LL2307170001材质',
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '条',
                        deputyUnit: null,
                        detailId: '58c796fa937d1e799184370cadad6f93',
                        drawingNo: 'LL2307170001图号',
                        gmtCreate: '2023-08-10 16:00:07',
                        id: '7d92a2dfbe50a4e06a4396d786dd5b86',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'bfefd2c6f790e582c2988d07df11e8f4',
                        materialName: 'LL2307170001',
                        materialNo: 'Material00172',
                        materialTypeName: '原材料',
                        model: 'LL2307170001型号',
                        region: null,
                        serialNo: 'Material00172-20230810-05',
                        sharpeningCount: 0,
                        specs: 'LL2307170001规格',
                        status: '1',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: 'LL2307170001材质',
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '条',
                        deputyUnit: null,
                        detailId: '4fde8eea9f3ef47c9637eaa4acb89593',
                        drawingNo: 'LL2307170001图号',
                        gmtCreate: '2023-08-10 16:00:07',
                        id: '7d92a2dfbe50a4e06a4396d786dd5b86',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'bfefd2c6f790e582c2988d07df11e8f4',
                        materialName: 'LL2307170001',
                        materialNo: 'Material00172',
                        materialTypeName: '原材料',
                        model: 'LL2307170001型号',
                        region: null,
                        serialNo: 'Material00172-20230810-04',
                        sharpeningCount: 0,
                        specs: 'LL2307170001规格',
                        status: '1',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: 'LL2307170001材质',
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '条',
                        deputyUnit: null,
                        detailId: 'ed5d3313ad8f5d021540a94fe06c673a',
                        drawingNo: 'LL2307170001图号',
                        gmtCreate: '2023-08-10 16:00:07',
                        id: '7d92a2dfbe50a4e06a4396d786dd5b86',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'bfefd2c6f790e582c2988d07df11e8f4',
                        materialName: 'LL2307170001',
                        materialNo: 'Material00172',
                        materialTypeName: '原材料',
                        model: 'LL2307170001型号',
                        region: null,
                        serialNo: 'Material00172-20230810-03',
                        sharpeningCount: 0,
                        specs: 'LL2307170001规格',
                        status: '5',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: 'LL2307170001材质',
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '条',
                        deputyUnit: null,
                        detailId: 'e53c997d09aa7ffe5852a22ab244593d',
                        drawingNo: 'LL2307170001图号',
                        gmtCreate: '2023-08-10 16:00:07',
                        id: '7d92a2dfbe50a4e06a4396d786dd5b86',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'bfefd2c6f790e582c2988d07df11e8f4',
                        materialName: 'LL2307170001',
                        materialNo: 'Material00172',
                        materialTypeName: '原材料',
                        model: 'LL2307170001型号',
                        region: null,
                        serialNo: 'Material00172-20230810-02',
                        sharpeningCount: 0,
                        specs: 'LL2307170001规格',
                        status: '5',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: 'LL2307170001材质',
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                    {
                        baseUnitId: 'ceda4dfe95ab9c361c557b75cd03e3ec',
                        baseUnitName: '套',
                        coatedCount: 0,
                        companyId: '56b33aabf97b4ebb9dd5ccb5bb5e8ff4',
                        companyName: '开发总公司',
                        cutThick: '20',
                        cutThickUnit: '条',
                        deputyUnit: null,
                        detailId: 'd470877b992c9c6455de36cdd39bd49e',
                        drawingNo: 'LL2307170001图号',
                        gmtCreate: '2023-08-10 16:00:07',
                        id: '7d92a2dfbe50a4e06a4396d786dd5b86',
                        isCoated: '1',
                        isSharpening: '1',
                        isUsedSerial: null,
                        materialId: 'bfefd2c6f790e582c2988d07df11e8f4',
                        materialName: 'LL2307170001',
                        materialNo: 'Material00172',
                        materialTypeName: '原材料',
                        model: 'LL2307170001型号',
                        region: null,
                        serialNo: 'Material00172-20230810-01',
                        sharpeningCount: 0,
                        specs: 'LL2307170001规格',
                        status: '4',
                        storageSpaceCount: null,
                        surplusCutThickness: 20.0,
                        texture: 'LL2307170001材质',
                        toolingType: '类别1',
                        warehouseId: '1b9c86f3149ddb0dac1d73879ed0d91f',
                        warehouseName: 'LL2306290002-李乐测试仓库勿用',
                    },
                ],
            },
        })
    })
}

const proTable = ref()
const resetQueryParam = () => {
    proTable.value.reset()
}
const getQueryParam = () => {
    console.log(proTable.value.getQueryParam())
}

// 主表列配置项
const columns = [
    {
        id: 'vj8LM5Kgfvoo8NiySLMDsn',
        label: '选择',
        prop: 'selection',
        type: 'selection',
        width: '60px',
        fixed: 'left',
        columnType: 2,
        searchProps: {
            enable: false,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: 'kCGidSbyVXxAymeU7kNjaD',
        label: '序号',
        prop: 'index1',
        type: 'index',
        width: '60px',
        fixed: 'left',
        columnType: 1,
        searchProps: {
            enable: false,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: '5bY13BW7UquGvfDjpD3mTb',
        label: '设备类别',
        prop: 'equipmentTypeName',
        sortable: true,
        fixed: 'left',
        columnType: 3,
        width: '130px',
        searchProps: {
            enable: true,
            componentType: 'tree',
            treeProps: { checkStrictly: false, disabledRoot: false },
            searchPropKey: 'EquipmentTypeId',
            dataSourceProps: { label: 'typeName', value: 'id', children: 'children' },
            dataSource: _params => {
                return new Promise(resolve => {
                    resolve({
                        code: 0,
                        data: [
                            {
                                children: [
                                    {
                                        children: [],
                                        disabled: false,
                                        eqpModelId: '366f8e79311ef6b88be80bcb03f33fc7',
                                        id: '366f8e79311ef6b88be80bcb03f33fc7',
                                        isEqpType: '否',
                                        parentId: 'c474ce1506cf5742ba6cc65418c301f0',
                                        typeCode: 'EqMod00010',
                                        typeCodeAndName: 'EqMod00010(sss)',
                                        typeName: 'sss',
                                        useBranchCompanyId: '688d7bc74b524a8da0fa03fcc654bd8a',
                                    },
                                    {
                                        children: [],
                                        disabled: false,
                                        eqpModelId: '5941af8d03084ea9e3a10ac2191e5225',
                                        id: '5941af8d03084ea9e3a10ac2191e5225',
                                        isEqpType: '否',
                                        parentId: 'c474ce1506cf5742ba6cc65418c301f0',
                                        typeCode: 'EqMod00018',
                                        typeCodeAndName: 'EqMod00018(011)',
                                        typeName: '011',
                                        useBranchCompanyId: 'd538e7de2b504dd8980d51d666f07086',
                                    },
                                    {
                                        children: [],
                                        disabled: false,
                                        eqpModelId: '893e61bf943060d65039fbb3a4e3a11c',
                                        id: '893e61bf943060d65039fbb3a4e3a11c',
                                        isEqpType: '否',
                                        parentId: 'c474ce1506cf5742ba6cc65418c301f0',
                                        typeCode: 'EqMod00005',
                                        typeCodeAndName: 'EqMod00005(主公司建的1)',
                                        typeName: '主公司建的1',
                                        useBranchCompanyId: 'c9161819339848fa95748df4155dc309',
                                    },
                                    {
                                        children: [],
                                        disabled: false,
                                        eqpModelId: '98029b95d20d2982b9392cb171341bf2',
                                        id: '98029b95d20d2982b9392cb171341bf2',
                                        isEqpType: '否',
                                        parentId: 'c474ce1506cf5742ba6cc65418c301f0',
                                        typeCode: 'EqMod00019',
                                        typeCodeAndName: 'EqMod00019(3)',
                                        typeName: '3',
                                        useBranchCompanyId: 'd538e7de2b504dd8980d51d666f07086',
                                    },
                                    {
                                        children: [],
                                        disabled: false,
                                        eqpModelId: '3db8315232d5008ea765dbe23490348c',
                                        id: '3db8315232d5008ea765dbe23490348c',
                                        isEqpType: '否',
                                        parentId: 'c474ce1506cf5742ba6cc65418c301f0',
                                        typeCode: 'EqMod00010',
                                        typeCodeAndName: 'EqMod00010(sss)',
                                        typeName: 'sss',
                                        useBranchCompanyId: 'd538e7de2b504dd8980d51d666f07086',
                                    },
                                    {
                                        children: [],
                                        disabled: false,
                                        eqpModelId: 'e599690a7fd8da64642ada33e8356173',
                                        id: 'e599690a7fd8da64642ada33e8356173',
                                        isEqpType: '否',
                                        parentId: 'c474ce1506cf5742ba6cc65418c301f0',
                                        typeCode: 'EqMod00010',
                                        typeCodeAndName: 'EqMod00010(sss)',
                                        typeName: 'sss',
                                        useBranchCompanyId: 'c9161819339848fa95748df4155dc309',
                                    },
                                    {
                                        children: [],
                                        disabled: false,
                                        eqpModelId: '22cf2ede8f56132784dc6429e0858fae',
                                        id: '22cf2ede8f56132784dc6429e0858fae',
                                        isEqpType: '否',
                                        parentId: 'c474ce1506cf5742ba6cc65418c301f0',
                                        typeCode: 'EqMod00020',
                                        typeCodeAndName: 'EqMod00020(早早)',
                                        typeName: '早早',
                                        useBranchCompanyId: 'd538e7de2b504dd8980d51d666f07086',
                                    },
                                    {
                                        children: [],
                                        disabled: false,
                                        eqpModelId: '035eb3f2ca8f06eba458be12b06b1e8a',
                                        id: '035eb3f2ca8f06eba458be12b06b1e8a',
                                        isEqpType: '否',
                                        parentId: 'c474ce1506cf5742ba6cc65418c301f0',
                                        typeCode: 'DR002',
                                        typeCodeAndName: 'DR002(第二个导入)',
                                        typeName: '第二个导入',
                                        useBranchCompanyId: 'd538e7de2b504dd8980d51d666f07086',
                                    },
                                    {
                                        children: [],
                                        disabled: false,
                                        eqpModelId: '355a970ace51786387455213c7c85a4c',
                                        id: '355a970ace51786387455213c7c85a4c',
                                        isEqpType: '否',
                                        parentId: 'c474ce1506cf5742ba6cc65418c301f0',
                                        typeCode: 'TTTX',
                                        typeCodeAndName: 'TTTX(激光切割100)',
                                        typeName: '激光切割100',
                                        useBranchCompanyId: 'd538e7de2b504dd8980d51d666f07086',
                                    },
                                    {
                                        children: [
                                            {
                                                children: [],
                                                disabled: false,
                                                eqpModelId: '2f5ff406447dcc03335f2dde607ef7dd',
                                                id: '2f5ff406447dcc03335f2dde607ef7dd',
                                                isEqpType: '否',
                                                parentId: '581e3cd803e32fce966621b3d7f1277c',
                                                typeCode: 'EqMod00009',
                                                typeCodeAndName: 'EqMod00009(xxxx333)',
                                                typeName: 'xxxx333',
                                                useBranchCompanyId:
                                                    'd538e7de2b504dd8980d51d666f07086',
                                            },
                                            {
                                                children: [],
                                                disabled: false,
                                                eqpModelId: '5bd0df73a662e71747b75546b2393f23',
                                                id: '5bd0df73a662e71747b75546b2393f23',
                                                isEqpType: '否',
                                                parentId: '581e3cd803e32fce966621b3d7f1277c',
                                                typeCode: 'EqMod00009',
                                                typeCodeAndName: 'EqMod00009(xxxx333)',
                                                typeName: 'xxxx333',
                                                useBranchCompanyId:
                                                    'c9161819339848fa95748df4155dc309',
                                            },
                                            {
                                                children: [],
                                                disabled: false,
                                                eqpModelId: 'e9c0ccb7a5765ca5740e7b07bda328f4',
                                                id: 'e9c0ccb7a5765ca5740e7b07bda328f4',
                                                isEqpType: '否',
                                                parentId: '581e3cd803e32fce966621b3d7f1277c',
                                                typeCode: 'EqMod00009',
                                                typeCodeAndName: 'EqMod00009(xxxx333)',
                                                typeName: 'xxxx333',
                                                useBranchCompanyId:
                                                    '688d7bc74b524a8da0fa03fcc654bd8a',
                                            },
                                            {
                                                children: [
                                                    {
                                                        children: [],
                                                        disabled: false,
                                                        eqpModelId:
                                                            '52ff8e7348191b2555b80b439235d9b6',
                                                        id: '52ff8e7348191b2555b80b439235d9b6',
                                                        isEqpType: '否',
                                                        parentId:
                                                            '3a66d23e5df1876b5cc3fd257d7bbda3',
                                                        typeCode: 'EqMod00007',
                                                        typeCodeAndName: 'EqMod00007(Lt0531002)',
                                                        typeName: 'Lt0531002',
                                                        useBranchCompanyId:
                                                            'd538e7de2b504dd8980d51d666f07086',
                                                    },
                                                    {
                                                        children: [],
                                                        disabled: false,
                                                        eqpModelId:
                                                            'c4a0e4ada63787abd69735b37403f44e',
                                                        id: 'c4a0e4ada63787abd69735b37403f44e',
                                                        isEqpType: '否',
                                                        parentId:
                                                            '3a66d23e5df1876b5cc3fd257d7bbda3',
                                                        typeCode: 'EqMod00008',
                                                        typeCodeAndName: 'EqMod00008(lt0531003)',
                                                        typeName: 'lt0531003',
                                                        useBranchCompanyId:
                                                            'd538e7de2b504dd8980d51d666f07086',
                                                    },
                                                    {
                                                        children: [],
                                                        disabled: false,
                                                        eqpModelId:
                                                            '90356cde87fac3f01daea28f19a7adab',
                                                        id: '90356cde87fac3f01daea28f19a7adab',
                                                        isEqpType: '否',
                                                        parentId:
                                                            '3a66d23e5df1876b5cc3fd257d7bbda3',
                                                        typeCode: 'EqMod00013',
                                                        typeCodeAndName: 'EqMod00013(lttest0531)',
                                                        typeName: 'lttest0531',
                                                        useBranchCompanyId:
                                                            'd538e7de2b504dd8980d51d666f07086',
                                                    },
                                                    {
                                                        children: [],
                                                        disabled: false,
                                                        eqpModelId:
                                                            '3ba35e32136ec4207c32c768c259a5d3',
                                                        id: '3ba35e32136ec4207c32c768c259a5d3',
                                                        isEqpType: '否',
                                                        parentId:
                                                            '3a66d23e5df1876b5cc3fd257d7bbda3',
                                                        typeCode: 'EqMod00014',
                                                        typeCodeAndName: 'EqMod00014(555)',
                                                        typeName: '555',
                                                        useBranchCompanyId:
                                                            'd538e7de2b504dd8980d51d666f07086',
                                                    },
                                                ],

                                                eqpModelId: null,
                                                id: '3a66d23e5df1876b5cc3fd257d7bbda3',
                                                isEqpType: '是',
                                                parentId: '581e3cd803e32fce966621b3d7f1277c',
                                                typeCode: 'EqCa00011',
                                                typeCodeAndName: 'EqCa00011(ccxx)',
                                                typeName: 'ccxx',
                                                useBranchCompanyId: null,
                                            },
                                        ],

                                        eqpModelId: null,
                                        id: '581e3cd803e32fce966621b3d7f1277c',
                                        isEqpType: '是',
                                        parentId: 'c474ce1506cf5742ba6cc65418c301f0',
                                        typeCode: 'EqCa00008',
                                        typeCodeAndName: 'EqCa00008(9)',
                                        typeName: '9',
                                        useBranchCompanyId: null,
                                    },
                                    {
                                        children: [
                                            {
                                                children: [],
                                                disabled: false,
                                                eqpModelId: '5b8ad05f31802314d4c705b160a2ca99',
                                                id: '5b8ad05f31802314d4c705b160a2ca99',
                                                isEqpType: '否',
                                                parentId: '8edcad903fb606af98099223c31273d9',
                                                typeCode: 'EqMod00004',
                                                typeCodeAndName: 'EqMod00004(Lt0531001)',
                                                typeName: 'Lt0531001',
                                                useBranchCompanyId:
                                                    'd538e7de2b504dd8980d51d666f07086',
                                            },
                                        ],

                                        eqpModelId: null,
                                        id: '8edcad903fb606af98099223c31273d9',
                                        isEqpType: '是',
                                        parentId: 'c474ce1506cf5742ba6cc65418c301f0',
                                        typeCode: 'EqCa00012',
                                        typeCodeAndName: 'EqCa00012(xiaoxxxs)',
                                        typeName: 'xiaoxxxs',
                                        useBranchCompanyId: null,
                                    },
                                    {
                                        children: [
                                            {
                                                children: [],
                                                disabled: false,
                                                eqpModelId: '6f7ede6fa0f34e5f2789da363d7f2e68',
                                                id: '6f7ede6fa0f34e5f2789da363d7f2e68',
                                                isEqpType: '否',
                                                parentId: '8fd23dc6dbe50de9c7a95776e1c8eb30',
                                                typeCode: 'EqMod00011',
                                                typeCodeAndName: 'EqMod00011(cds)',
                                                typeName: 'cds',
                                                useBranchCompanyId:
                                                    'd538e7de2b504dd8980d51d666f07086',
                                            },
                                        ],

                                        eqpModelId: null,
                                        id: '8fd23dc6dbe50de9c7a95776e1c8eb30',
                                        isEqpType: '是',
                                        parentId: 'c474ce1506cf5742ba6cc65418c301f0',
                                        typeCode: 'EqCa00003',
                                        typeCodeAndName: 'EqCa00003(zzzz)',
                                        typeName: 'zzzz',
                                        useBranchCompanyId: null,
                                    },
                                    {
                                        children: [],

                                        eqpModelId: null,
                                        id: 'd37747cda9f4194b73cd598cff037200',
                                        isEqpType: '是',
                                        parentId: 'c474ce1506cf5742ba6cc65418c301f0',
                                        typeCode: '',
                                        typeCodeAndName: '(csddd)',
                                        typeName: 'csddd',
                                        useBranchCompanyId: null,
                                    },
                                ],

                                eqpModelId: null,
                                id: 'c474ce1506cf5742ba6cc65418c301f0',
                                isEqpType: '是',
                                parentId: '-1',
                                typeCode: 'EqCa00002',
                                typeCodeAndName: 'EqCa00002(qqqq1123345)',
                                typeName: 'qqqq1123345',
                                useBranchCompanyId: null,
                            },
                        ],
                        msg: '操作成功',
                        ok: true,
                        stackMsg: null,
                    })
                })
            },
            supportConditionList: ['in', 'isNull', 'notIn', 'isNotNull'],
        },
    },
    {
        id: 'hvMbFmYZcPfQDfc4gX7nGf',
        label: '物料编码',
        prop: 'materialNo',
        width: '140px',
        fixed: 'left',
        columnType: 3,
        searchProps: {
            enable: true,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: 'hDMXBQga7q8y5EQoXD38Ej',
        label: '物料名称',
        prop: 'materialName',
        width: '140px',
        fixed: 'left',
        columnType: 3,
        searchProps: {
            enable: true,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: 'rNqkRebQ3h9eGyG4hC1HiL',
        label: '序列号',
        prop: 'serialNo',
        width: '140px',
        fixed: 'left',
        columnType: 3,
        showOverflowTooltip: true,
        searchProps: {
            enable: true,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: 'uPfmLMKGCprBwNDVWp9DCV',
        label: '物料类别',
        prop: 'materialTypeName',
        width: '140px',
        columnType: 3,
        searchProps: {
            enable: false,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: 'jkkKrP6d97ckeBh8FtCpXj',
        label: '刀具类别',
        prop: 'toolingType',
        width: '100px',
        columnType: 3,
        searchProps: {
            enable: true,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: '5Eu5HHLB5QKHo2T5XZGRap',
        label: '规格',
        prop: 'specs',
        width: '140px',
        columnType: 3,
        searchProps: {
            enable: true,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: 'wcfJ4Kh5gxH4jofdtyP8fa',
        label: '型号',
        prop: 'model',
        width: '140px',
        columnType: 3,
        searchProps: {
            enable: true,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: 'uF65kesgc77ob87Mb12Hmi',
        label: '材质',
        prop: 'texture',
        width: '140px',
        columnType: 3,
        searchProps: {
            enable: true,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: '6VtLpDpEr7UDLQbxaJAG45',
        label: '图号',
        prop: 'drawingNo',
        width: '140px',
        columnType: 3,
        searchProps: {
            enable: true,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: 'mZT4ab8RqmgVQtN8dg9yaE',
        label: '工厂',
        prop: 'companyName',
        width: '140px',
        columnType: 3,
        searchProps: {
            enable: false,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: '1B4GBRHRdpU8AegFHCkb9M',
        label: '是否刃磨',
        prop: 'isSharpening',
        width: '140px',
        columnType: 3,
        dictId: 'InnerDictStartOrStop',
        searchProps: {
            enable: true,
            componentType: 'select',
            supportConditionList: ['isNull', 'isNotNull', 'notIn', 'in'],
        },
    },
    {
        id: 'bwhG8H93q4XuVRxvKvh86A',
        label: '切削刃厚度',
        prop: 'cutThick',
        width: '140px',
        columnType: 3,
        searchProps: {
            enable: false,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: 'gCaPTEMPc1AXxgLGRFAduh',
        label: '切削刃厚度单位',
        prop: 'cutThickUnit',
        width: '160px',
        columnType: 3,
        searchProps: {
            enable: false,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: 'piPZk6d6woeZ6hKNQz49Ap',
        label: '切削刃剩余厚度',
        prop: 'surplusCutThickness',
        width: '160px',
        columnType: 3,
        searchProps: {
            enable: true,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: 'nWsQbVBZxj844ZTWqNQLG9',
        label: '累计刃磨次数',
        prop: 'sharpeningCount',
        width: '160px',
        columnType: 3,
        searchProps: {
            enable: true,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: 'uczkaiWMtmZEFMrhyUDPfC',
        label: '是否涂层',
        prop: 'isCoated',
        width: '140px',
        columnType: 3,
        dictId: 'InnerDictStartOrStop',
        searchProps: {
            enable: false,
            componentType: 'select',
            supportConditionList: ['isNull', 'isNotNull', 'notIn', 'in'],
        },
    },
    {
        id: '3hsn7jndKAgJLxF7hW4N1D',
        label: '涂层次数',
        prop: 'coatedCount',
        width: '100px',
        columnType: 3,
        searchProps: {
            enable: true,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
    {
        id: 'kE1DH287ThyfiNN8DNKee6',
        label: '状态',
        prop: 'status',
        width: '100px',
        columnType: 3,
        dictId: 'INNER_TOOING_LEDGER_STATUS',
        searchProps: {
            enable: true,
            componentType: 'select',
            supportConditionList: ['isNull', 'isNotNull', 'notIn', 'in'],
        },
    },
    {
        id: 'nHrE68QEuAxAgE7fo9tZ7T',
        label: '操作',
        prop: 'operate',
        width: '120px',
        fixed: 'right',
        columnType: 4,
        searchProps: {
            enable: false,
            componentType: 'text',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
        },
    },
]
// const columns = [
//     {
//         id: 'kqCSuhjERb86oRCRn6thby',
//         label: '筛选',
//         prop: 'column1671091239095',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.column1671091239095',
//         type: 'selection',
//         width: '60px',
//         fixed: 'left',
//         columnType: 2,
//         reserveSelection: true,
//         searchProps: {
//             enable: false,
//             componentType: 'text',
//             supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
//         },
//     },
//     {
//         id: '1ZEpYGDJ2EL74vbeBimjmN',
//         label: '序号',
//         prop: 'column1671091239094',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.column1671091239094',
//         type: 'index',
//         width: '60px',
//         fixed: 'left',
//         columnType: 1,
//         searchProps: {
//             enable: false,
//             componentType: 'text',
//             supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
//         },
//     },
//     {
//         id: 'hFJHpW1egad392vSTNoYNw',
//         label: '设备机型编码',
//         prop: 'modelCode',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.ModelCode',
//         width: '150px',
//         fixed: 'left',
//         columnType: 3,
//         searchProps: {
//             enable: true,
//             componentType: 'text',
//             supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
//             searchVisible: true,
//         },
//     },
//     {
//         id: 'kaep3dKChDdswZZMdSK3dz',
//         label: '设备机型名称',
//         prop: 'modelName',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.ModelName',
//         width: '150px',
//         fixed: 'left',
//         columnType: 3,
//         searchProps: {
//             enable: true,
//             componentType: 'text',
//             supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
//             searchVisible: true,
//         },
//     },
//     {
//         id: 'd3mrp7qcC4XLHohjwFZgtU',
//         label: '设备类别',
//         prop: 'typeName',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.TypeName',
//         width: '100px',
//         columnType: 3,
//         searchProps: {
//             enable: true,
//             componentType: 'tree',
//             searchPropKey: 'eqpTypeId',
//             dataSourceProps: {
//                 label: 'typeName',
//                 value: 'id',
//             },
//             supportConditionList: ['in', 'isNull', 'notIn', 'isNotNull'],
//             searchVisible: true,
//         },
//     },
//     {
//         id: '61BsQbg98DWwGTzpDXcrWd',
//         label: '型号',
//         prop: 'model',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.Model',
//         width: '100px',
//         columnType: 3,
//         searchProps: {
//             enable: true,
//             componentType: 'text',
//             supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
//             searchVisible: true,
//         },
//     },
//     {
//         id: 'tGePLHodY7Q7kESpnf786e',
//         label: '规格',
//         prop: 'specs',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.Specs',
//         width: '100px',
//         columnType: 3,
//         searchProps: {
//             enable: true,
//             componentType: 'text',
//             supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
//             searchVisible: true,
//         },
//     },
//     {
//         id: 'ckDTeQ31c65oVSxbPxed4y',
//         label: '单位',
//         prop: 'unitName',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.UnitName',
//         width: '100px',
//         columnType: 3,
//         searchProps: {
//             enable: true,
//             componentType: 'text',
//             supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
//             searchVisible: true,
//         },
//     },
//     {
//         id: 'sQzb6qeqHXYmWCTwdcbRNk',
//         label: '品牌',
//         prop: 'brand',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.Brand',
//         width: '100px',
//         columnType: 3,
//         searchProps: {
//             enable: true,
//             componentType: 'text',
//             supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
//             searchVisible: true,
//         },
//     },
//     {
//         id: 'vaAcU9A1fFigb1BYPdfbAn',
//         label: '特种设备',
//         prop: 'isSpecial',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.IsSpecial',
//         width: '120px',
//         columnType: 3,
//         dictId: 'SysYesNo',
//         searchProps: {
//             enable: true,
//             componentType: 'select',
//             supportConditionList: ['notIn', 'isNull', 'isNotNull', 'in'],
//             searchVisible: true,
//         },
//     },
//     {
//         id: 'hpVL2tKe3RyrZ47urX4GpG',
//         label: '使用状态',
//         prop: 'useStatus',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.UseStatus',
//         width: '100px',
//         columnType: 3,
//         dictId: 'SysStatus',
//         searchProps: {
//             enable: true,
//             componentType: 'select',
//             supportConditionList: ['notIn', 'isNull', 'isNotNull', 'in'],
//             searchVisible: true,
//         },
//     },
//     {
//         id: 'eMUZ6axsVgKYXrWpqunAYq',
//         label: '创建组织',
//         prop: 'branchCompanyName',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.BranchCompanyName',
//         width: '150px',
//         columnType: 3,
//         searchProps: {
//             enable: true,
//             componentType: 'tree',
//             searchPropKey: 'branchCompanyId',
//             supportConditionList: ['in', 'isNull', 'notIn', 'isNotNull'],
//             searchVisible: true,
//         },
//     },
//     {
//         id: 'mxcdKY8mhD5cWL76CeU8X1',
//         label: '使用组织',
//         prop: 'useBranchCompanyName',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.UseBranchCompanyName',
//         width: '150px',
//         columnType: 3,
//         searchProps: {
//             enable: false,
//             componentType: 'text',
//             supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
//         },
//     },
//     {
//         id: 'sJYxn1kwQYKGUyoS2jbmUC',
//         label: '分配组织',
//         prop: 'distributedNum',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.distributedNum',
//         width: '100px',
//         columnType: 3,
//         searchProps: {
//             enable: true,
//             componentType: 'number',
//             supportConditionList: [
//                 'ne',
//                 'isNull',
//                 'isNotNull',
//                 'gele',
//                 'le',
//                 'lt',
//                 'gt',
//                 'ge',
//                 'eq',
//             ],
//             searchVisible: true,
//         },
//     },
//     {
//         id: 'uD6oCoJGbxd8qeBZbVPRfd',
//         label: '创建人',
//         prop: 'creatorName',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.CreatorName',
//         width: '150px',
//         columnType: 3,
//         searchProps: {
//             enable: true,
//             componentType: 'text',
//             supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
//             searchVisible: true,
//         },
//     },
//     {
//         id: '3URsFoGK1Czy3sSwxx9uc4',
//         label: '创建时间',
//         prop: 'gmtCreate',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.GmtCreate',
//         width: '180px',
//         columnType: 3,
//         searchProps: {
//             enable: true,
//             componentType: 'datetime',
//             supportConditionList: [
//                 'le',
//                 'lt',
//                 'isNotNull',
//                 'gele',
//                 'gt',
//                 'ge',
//                 'ne',
//                 'eq',
//                 'isNull',
//             ],
//             searchVisible: true,
//         },
//     },
//     {
//         id: 'vzA1sFrz7zvYcSpYF92Ajh',
//         label: '密级',
//         prop: 'securityLevel',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.SecurityLevel',
//         width: '100px',
//         columnType: 3,
//         dictId: 'INNER_DICT_ConfidentialityLevel',
//         searchProps: {
//             enable: true,
//             componentType: 'select',
//             supportConditionList: ['notIn', 'isNull', 'isNotNull', 'in'],
//             searchVisible: true,
//         },
//     },
//     {
//         id: '9Nv1JjmaZDc1tMGEiuqnwF',
//         label: '备注',
//         prop: 'remark',
//         i18nKey: 'EquipmentModeling.EquipmentModelingTable.Remark',
//         width: '100px',
//         columnType: 3,
//         searchProps: {
//             enable: false,
//             componentType: 'text',
//             supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull'],
//         },
//     },
// ]

// 子表列配置项
const slavecolumns = [
    {
        id: '19eba15d3b7542318d32efcf467b3e3f',
        label: '子表1',
        prop: 'name',
        i18nKey: '',
        hidden: 0,
        align: 'left',
        sortable: 0,
        columnType: 3,
        searchProps: {
            searchVisible: false, // 用于弹窗里该项选择后禁用
            enable: true,
            componentType: 'text',
            searchPropKey: 'ModifiedId2',
            supportConditionList: ['ne', 'like', 'eq', 'isNull', 'notlike', 'isNotNull', 'gele'],
        },
    },
    {
        id: '2b1dada90122484387c333c25e9f3df6',
        label: '子表2',
        prop: 'entityName',
        i18nKey: '',
        width: '200px',
        hidden: 0,
        align: 'left',
        sortable: 0,
        columnType: 3,
        searchProps: {
            searchVisible: false,
            enable: true,
            componentType: 'date',
            realProp: 'userId',
            supportConditionList: [
                'in',
                'ne',
                'like',
                'eq',
                'isNull',
                'notlike',
                'isNotNull',
                'gele',
            ],
        },
    },
]
//主表
const masterSearchColumns = []
//主表所有字段
masterSearchColumns.push(...columns)
//追加子表所有字段，也可单独加个别的
masterSearchColumns.push(...slavecolumns)

// 默认方案
const senceInfo = ref({
    defaultSence: '1', // 默认方案（取方案的id）
    senceList: [
        {
            name: '默认方案',
            id: '1',
            active: false, // 是否选中激活
            edit: false, // 是否可编辑
            canDel: false, // 是否可删除
            innerSence: true, // 是否内置方案
            setDefaultSence: true, // 是否默认
            allExpose: false, // 是否全部外露
            searchList: [
                {
                    id: 'hvMbFmYZcPfQDfc4gX7nGf',
                    searchCondition: 'like',
                    searchValue: [],
                    searchVisible: true,
                },
            ],
        },
        {
            name: '方案11',
            id: '2',
            active: true, // 是否选中激活
            edit: false, // 是否可编辑
            canDel: true, // 是否可删除
            innerSence: false, // 是否内置方案
            setDefaultSence: false, // 是否默认
            allExpose: false, // 是否全部外露
            searchList: [],
        },
        {
            name: '方案22',
            id: '3',
            active: false, // 是否选中激活
            edit: false, // 是否可编辑
            canDel: true, // 是否可删除
            innerSence: false, // 是否内置方案
            setDefaultSence: false, // 是否默认
            allExpose: false, // 是否全部外露
            searchList: [],
        },
    ],
})
const searchBarChange = val => {
    console.log(val, 'searchBarChange...')
}
</script>
<style lang="scss">
@import '@beeboat/theme/src/bt-table';
</style>
